### PR TITLE
Use Ruby autoload to lower memory usage and load times

### LINKED ISSUE #13: Intersight ruby client require is very expensive (8 seconds, 400 MB, 6000 loaded files)
I was playing around with i18n on manageiq and noticed one rake task was extremely slow.  Digging into it, I found that a simple require of the [intersight client](https://github.com/ManageIQ/manageiq-providers-cisco_intersight/blob/48b25ac95868467c9d09cedffd1d97d4103d92d2/app/models/manageiq/providers/cisco_intersight/manager_mixin.rb#L1) was taking several seconds.

I wrote a script to recreate it. You may have to `gem install the sys-proctable` gem if you don't have it locally:

```
% ruby -e 'require "sys/proctable"; puts "memory before: #{Sys::ProcTable.ps(:pid => Process.pid).rss}"; puts "loaded features: #{$LOADED_FEATURES.length}"; puts Time.now; puts "requiring intersight_client"; require "intersight_client"; puts "loaded features: #{$LOADED_FEATURES.length}"; puts Time.now; puts "memory before: #{Sys::ProcTable.ps(:pid => Process.pid).rss}"'

memory before: 15732736
loaded features: 73
2022-06-21 15:22:11 -0400
requiring intersight_client
loaded features: 6165
2022-06-21 15:22:19 -0400
memory before: 422789120
```

Basically, it takes me 8 seconds to do: `require "intersight_client"`
Additionally, it consumes over 400 MB of memory and requires nearly 6000 files.

This is because we're doing "eager" requires here:  https://github.com/xlab-si/intersight-sdk-ruby/blob/main/lib/intersight_client.rb#L14-L5947

I know this gem is generated from openapi but we should look to see if there are ways we can either delay load this using `autoload` (be careful if you're using threads) or do all of these requires when initializing the first "client" object, exposing only the `Client.new` on the normal require.

Some gems will have a skeleton require that exposes the basics and when you first create a client or some objects from this gem, you'd then do a `require/all` or similar to avoid doing this painful require until we're in processes that are actually using the client.

### PR DESCRIPTION
**Pull request by Fryguy**
Fixes #13

Some performance numbers (on my Mac)

Before:
  Time for `require "intersight_client"`: ~6.6
  Memory Usage: ~390MB

After:
  Time for `require "intersight_client"`: ~0.29s
  Memory Usage: ~21MB

  As we load the constants one-by-one memory will approach the Before
  numbers, but it will be on-demand, and most people won't use all of
  the constants.

Table of loading constants one-by-one: https://gist.github.com/Fryguy/c1ace071c5e2a7c796027ffb7c98c1d9

Nice side effect also is that the reorder-requires.sh script takes a long time to run because of the way it does nested greps in a loop, however the new script is near-instant, because order doesn't matter.  So, builds take that much less time.

@zitnik @alescernivec Please review.

### CODE REVIEW

**Comment by Fryguy** [comment]
Note that ordering the requires like before is not required because ruby will naturally load them in the correct order on demand.

**Comment by Fryguy** [comment]
I can get the memory down to 10 MB by autoloading the ApiClient, but that will require a more complicated script, so I'm happy with 20MB for now.  In normal use cases when you require the gem you're probably going to use it immediately, meaning you will be loading the client anyway.

**Comment by jrafanie** [comment]
I would feel more comfortable if we can do something like:

Before this PR:

```
require 'intersight_client
puts $LOADED_FEATURES.sort
```

After this PR:

```
require 'intersight_client
# enumerate all of the files and load them
# compare the loaded features after
puts $LOADED_FEATURES.sort
```

It might be handy to create a file that eager loads all of the autoloaded files for testing or if an entrypoint that intends to use this gem wants to load everything.

**Comment by Fryguy** [comment]
I implied it in the OP, but I did load every constant one-by-one and checked the memory afterwards, but the chart is 6000 lines long, so just too long to present.

---

Before:

```
[2] pry(main)> orig_loaded_features = $LOADED_FEATURES.dup
[3] pry(main)> require "intersight_client"
[4] pry(main)> ($LOADED_FEATURES - orig_loaded_features).size
=> 6085
```

After:

```
[2] pry(main)> orig_loaded_features = $LOADED_FEATURES.dup
[2] pry(main)> require "intersight_client"
[3] pry(main)> ($LOADED_FEATURES - orig_loaded_features).size
=> 155
[4] pry(main)> IntersightClient.constants.each { |c| IntersightClient.const_get(c) }; nil
[5] pry(main)> ($LOADED_FEATURES - orig_loaded_features).size
=> 6085
```

**Comment by Fryguy** [comment]
Opened https://github.com/OpenAPITools/openapi-generator/pull/12680 to push these similar changes into the generator itself.  Once that's in, and this gem starts using the latest openapi-generator, then we can complete remove the patches.

**Comment by zitnik** [comment]
Thanks @Fryguy, this looks great.
Being a noob in ruby, I didn't even know about the autoload feature.
Also good that we can remove that bash-grep mess of mine :)

**Comment by zitnik** [comment]
@jrafanie Done.

**Comment by jrafanie** [comment]
Thanks @zitnik!

**Pull request merged**
